### ISSUE TITLE
Missing .obelisk/impl file?

### ISSUE THREAD

**Issue by endgame** [qfpl/reflex-workshop#8]
When I try to build the VM (on lark) via `nix-build nix/release.nix`, I get:
```
error: getting status of '/home/endgame/reflex-workshop/.obelisk/impl': No such file or directory
```

**Comment by dalaing** [comment]
That was a dead file, which I've since removed.  Hopefully `nix-build nix/vm.nix` will give you what you want (although it is also available [here](https://hydra.qfpl.io/job/reflex-workshop/reflex-workshop/reflex-workshop-vm/latest/download/1)).

**Comment by endgame** [comment]
Seems OK. I'm getting an error at the end of the build, but that's not the fault of this, and could be a nix configuration thing.
